workflows:
  flutter-workflow:
    name: Flutter Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        PROJECT_NAME: my_new_app
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Analyze code
        script: |
          flutter analyze
      - name: Run tests
        script: |
          flutter test
      - name: Build APK
        script: |
          flutter build apk --release
      - name: Build AppBundle (Optional)
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
    publishing:
      google_play:
        service_account: $GOOGLE_PLAY_SERVICE_ACCOUNT
        track: internal
        artifact_path: build/app/outputs/bundle/release/app-release.aab
